### ISSUE TITLE
More Appropiate Http Status Codes

### ISSUE THREAD

**Issue by erikspall** [TimoReusch/studentenwerk-wuerzburg-mensa-api#42]
For example, if a canteen does not have a menu 404 should NOT be returned. 404 should only be returned if the canteenId was not found. This way one can represent errors in an app more accurately

**Comment by TimoReusch** [comment]
@erikspall Which status code would you pick? Imho 404 is best suited for both cases, however different error messages should be provided.

**Comment by erikspall** [comment]
Reiterating on my thoughts I think 404 is appropriate if the foodProviderId exists.

If the foodProviderId does not exist, I suggest using the 400 Bad request status.

See [400 Bad request](https://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes#400)

**Comment by TimoReusch** [comment]
Sounds good to me! 😄
